### ISSUE TITLE
Prune branches for paper templates?

### ISSUE THREAD

**Issue by chitrams** [idem-lab/conmat#168]
Non-urgent, but thought it might make things easier. There are currently three branches for the JOSS paper and sometimes it's confusing which one is used? Shall we prune the branches and have just the one?

- [add-paper-template](https://github.com/idem-lab/conmat/tree/add-paper-template)
- [add-joss-paper](https://github.com/idem-lab/conmat/tree/add-joss-paper)
- [add-joss-paper-135](https://github.com/idem-lab/conmat/tree/add-joss-paper)

I've forked add-paper-template as [draft-JOSS](https://github.com/chitrams/conmat/tree/draft-JOSS) to make things even more confusing, sorry. This is where the most recent changes to the JOSS paper currently lives.

**Comment by chitrams** [comment]
PR #162 is the JOSS paper updates from me :)

**Comment by MikeLydeamore** [comment]
I think we can just keep the currently updated one and delete the others.

**Comment by njtierney** [comment]
These have been pruned!
