### ISSUE TITLE
Update Prem Germany matrices

### ISSUE THREAD

**Issue by njtierney** [idem-lab/conmat#174]
- [x] Find excel files (I think here? https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1009098#sec010)
- [x] Update data-raw/prem/MUestimates_home/work/schoo/other_locations.xlsx
- [x] Update cleaning code used https://github.com/idem-lab/conmat/blob/86a8702ab6bf4b840b6177ccc62ae67fb7698cb9/data-raw/prem_germany_contact_matrices.R
- [x] Update documentation https://github.com/idem-lab/conmat/blob/86a8702ab6bf4b840b6177ccc62ae67fb7698cb9/R/data_prem_contact_matrices.R to use updated DOI, and also note that it has been updated to use latest corrected matrices

**Comment by chitrams** [comment]
- [ ] Need to check if transposition (to, from) is correct
